### ISSUE TITLE
RecursionError

### ISSUE THREAD

**Issue by roflcoopter** [dale3h/python-lovelace#3]
Dying to try this out but i cant get it to work.

I get this error 
```  
Traceback (most recent call last):
  File "lovelace_migrate.py", line 844, in <module>
    sys.exit(main())
  File "lovelace_migrate.py", line 798, in main
    lovelace = Lovelace(states_json, title=args.title)
  File "lovelace_migrate.py", line 562, in __init__
    views.pop('default_view')))
  File "lovelace_migrate.py", line 129, in from_config
    return fx(config)
  File "lovelace_migrate.py", line 205, in from_group_config
    card = Lovelace.Card.from_config(entity)
  File "lovelace_migrate.py", line 234, in from_config
    return cls.from_config(config)
  File "lovelace_migrate.py", line 229, in from_config
    return super().from_config(config)
  File "lovelace_migrate.py", line 129, in from_config
    return fx(config)
.................
  File "lovelace_migrate.py", line 273, in from_group_config
    control = group['attributes'].get('control') != 'hidden'
RecursionError: maximum recursion depth exceeded in comparison
```
Any idea what might be wrong?

**Comment by dale3h** [comment]
Is it possible that you have a group listed as an entity inside of itself?

**Comment by roflcoopter** [comment]
You are very much correct, i temporarily commented it out and now it worked like a charm. Great job on this!
